oc.thread.on("MessageAdded", async function ({message}) {
      message.content = message.content.replaceAll("a", "a̷͌̄͜")
      message.content = message.content.replaceAll("b", "b̶͔̚")
      message.content = message.content.replaceAll("c", "c̷̤͌")
      message.content = message.content.replaceAll("d", "d̶͎͂")
      message.content = message.content.replaceAll("e", "e̷͖͋")
      message.content = message.content.replaceAll("f", "f̶͇͑")
      message.content = message.content.replaceAll("g", "g̵̥͠")
      message.content = message.content.replaceAll("h", "ḩ̸̅")
      message.content = message.content.replaceAll("i", "i̵̞̚")
      message.content = message.content.replaceAll("j", "j̷̘̔")
      message.content = message.content.replaceAll("k", "k̷̠̊")
      message.content = message.content.replaceAll("l", "ĺ̵̻")
      message.content = message.content.replaceAll("m", "m̶̡͝")
      message.content = message.content.replaceAll("n", "n̶͕͘")
      message.content = message.content.replaceAll("o", "o̵̰̍")
      message.content = message.content.replaceAll("p", "p̷͕̌")
      message.content = message.content.replaceAll("q", "q̶̭̊")
      message.content = message.content.replaceAll("r", "r̸̯̈́")
      message.content = message.content.replaceAll("s", "s̷̄̃")
      message.content = message.content.replaceAll("t", "t̵̻́")
      message.content = message.content.replaceAll("u", "u̵̱͋")
      message.content = message.content.replaceAll("v", "ṿ̷̓")
      message.content = message.content.replaceAll("w", "w̸̪͊")
      message.content = message.content.replaceAll("x", "x̶͕̌̏")
      message.content = message.content.replaceAll("y", "y̴̺̗̤͊̍̀")
      message.content = message.content.replaceAll("z", "z̴̺̣̟̄̊")
});
      